/*
 * Agora Digital Solutions Inc.
 *************************************************************************************
 * Copyright 2020 Agora Digital Solutions Inc.

 * All rights reserved in Agora Digital Solutions Inc. authored and generated code (including the selection and arrangement of the source code base regardless of the authorship of individual files), but not including any copyright interest(s) owned by a third party related to source code or object code authored or generated by non- Agora Digital Solutions Inc. personnel.
 * Any use, disclosure and/or reproduction of source code is prohibited unless in compliance with the AGORA SOFTWARE DEVELOPMENT KIT LICENSE AGREEMENT.
 *
 */

#ifndef FlowSensor_HPP
#define FlowSensor_HPP

#include "IAppManager.hpp"
#include "IBusClient.hpp"
#include "DirectMethodHndlr.hpp"
#include "DataHndlr.hpp"
#include "PropChngHndlr.hpp"
#include "flow_velocity.hpp"

class FlowSensor : public IAppManager, public DataInHndlr, public PropChngHndlr
{

public:
	~FlowSensor();
	int Execute(int ArgCount, char* ArgValues[]);
	CModuleComponent * GetInstance();
	const std::string GetName();
	const std::string GetVersion();
	int Initialize(std::string Configuration);
	void Restart();
	int Terminate();

	int HandleData(std::string & payload);
	int HandleProp(std::string & payload);

protected:
    FlowSensor();

	static FlowSensor gAppMgrInstance;

    virtual void SetName(std::string Name);
	virtual void SetVersion(std::string Version);
	
private:

	bool m_Run;
	std::string m_ModuleModel;
	std::string m_Name;
	std::string m_Version;

	std::string m_DataInEndpoint;
	std::string m_DataOutEndpoint;

	std::vector<std::string> m_Methods;

	DirectMethodHndlr* m_DirectMethodCall1;
	DirectMethodHndlr* m_DirectMethodCall2;

	DataInHndlr* m_EndPoint1Hndlr;

	PropChngHndlr* m_PropertyChangeHndlr;

	StateRspnsHndlr* m_StateRspnsHndlr;
	
	hbm::JSerializer m_DataSerializer;
	hbm::JSerializer m_ConfigSerializer;

	CAlgorithm* m_Algorithm;

};
#endif /* FlowSensor_HPP */
